services:
  backend:
    build: ./backend
    network_mode: host
    environment:
      - NODE_ENV=development
      - KUBECONFIG=/root/.kube/config
      - DEMO_MODE=false
    volumes:
      - ${HOME}/.kube:/root/.kube:ro
      - ${HOME}/.minikube:/root/.minikube:ro
  frontend:
    build: ./frontend
    network_mode: host
    depends_on:
      - backend
networks:
  app: {}
